/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AlifM
 */
public class Soal4 extends javax.swing.JFrame {

    /**
     * Creates new form Soal4
     */
    public Soal4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        penuh = new javax.swing.JRadioButton();
        kosong = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        setengah = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        buttonGroup1.add(penuh);
        penuh.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        penuh.setText("Penuh");
        getContentPane().add(penuh);
        penuh.setBounds(90, 130, 80, 30);

        buttonGroup1.add(kosong);
        kosong.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        kosong.setText("Kosong");
        kosong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kosongActionPerformed(evt);
            }
        });
        getContentPane().add(kosong);
        kosong.setBounds(90, 190, 110, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("<html>  Berapa banyakkah air didalam pot tersebut ?  </html>");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 80, 380, 60);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Lhat Hasilnya");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 250, 140, 30);

        buttonGroup1.add(setengah);
        setengah.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setengah.setText("Setengah");
        setengah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setengahActionPerformed(evt);
            }
        });
        getContentPane().add(setengah);
        setengah.setBounds(90, 160, 140, 30);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setText("SOAL 4");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 60, 120, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\Water-1600x900.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 400, 290);

        setBounds(500, 200, 416, 327);
    }// </editor-fold>//GEN-END:initComponents

    private void kosongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kosongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kosongActionPerformed

    private void setengahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setengahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setengahActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String hasil4;

        if(penuh.isSelected())
            hasil4 = "Cita-cita Anda sudah tercapai. Selamat ya !";
        else if(setengah.isSelected())
            hasil4 = "Cita-cita baru tercapai sebagian.";
        else
            hasil4 = "Cita-cita Anda belum tercapai. Selamat berjuang !";

        new Hasil4(hasil4).setVisible(true);  
         dispose();    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soal4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soal4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soal4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soal4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soal4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton kosong;
    private javax.swing.JRadioButton penuh;
    private javax.swing.JRadioButton setengah;
    // End of variables declaration//GEN-END:variables
}
