/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AlifM
 */
public class Soal2 extends javax.swing.JFrame {

    /**
     * Creates new form Soal2
     */
    public Soal2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        bulat = new javax.swing.JRadioButton();
        Segitiga = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Kotak = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setText("SOAL 2");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 120, 30);

        buttonGroup1.add(bulat);
        bulat.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bulat.setText("Bulat");
        getContentPane().add(bulat);
        bulat.setBounds(20, 140, 120, 30);

        buttonGroup1.add(Segitiga);
        Segitiga.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Segitiga.setText("Segitiga");
        Segitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SegitigaActionPerformed(evt);
            }
        });
        getContentPane().add(Segitiga);
        Segitiga.setBounds(290, 140, 80, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("<html> \nLalu Anda masuk ke gubuk tersebut dan Anda melihat sebuah meja. <br> <br>\n\nApa bentuk meja tersebut?\n\n</html>");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 380, 60);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Lihat Hasilnya");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 250, 150, 30);

        buttonGroup1.add(Kotak);
        Kotak.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Kotak.setText("Kotak");
        Kotak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KotakActionPerformed(evt);
            }
        });
        getContentPane().add(Kotak);
        Kotak.setBounds(150, 140, 90, 30);

        setBounds(500, 200, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void SegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SegitigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SegitigaActionPerformed

    private void KotakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KotakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KotakActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String hasil2;

        if(bulat.isSelected())
            hasil2 = "Anda berteman dengan siapa saja. Masa sih ?";
        else if(Kotak.isSelected())
            hasil2 = "Anda selektif dalam berteman.";
        else
            hasil2 = "Sangat pemilih dalam berteman.";

        new Hasil2(hasil2).setVisible(true);  
        dispose();    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Kotak;
    private javax.swing.JRadioButton Segitiga;
    private javax.swing.JRadioButton bulat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
