/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AlifM
 */
public class soal9 extends javax.swing.JFrame {

    /**
     * Creates new form soal9
     */
    public soal9() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        besar = new javax.swing.JRadioButton();
        kecil = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        sedang = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        besar.setBackground(new java.awt.Color(255, 255, 255));
        besar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        besar.setText("Besar");
        getContentPane().add(besar);
        besar.setBounds(10, 100, 200, 30);

        kecil.setBackground(new java.awt.Color(255, 255, 255));
        kecil.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        kecil.setText("Kecil");
        kecil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kecilActionPerformed(evt);
            }
        });
        getContentPane().add(kecil);
        kecil.setBounds(10, 160, 160, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<html>  Lalu Anda keluar dari istana tadi dan melihat sebuah kotak harta karun. Bagaimana ukuran kotak tersebut?  </html>");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 380, 60);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Lihat Hasilnya");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 250, 140, 30);

        sedang.setBackground(new java.awt.Color(255, 255, 255));
        sedang.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        sedang.setText("Sedang");
        sedang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sedangActionPerformed(evt);
            }
        });
        getContentPane().add(sedang);
        sedang.setBounds(10, 130, 140, 30);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SOAL 9");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 120, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\a84444f22cea21a83319a0e87a2b2d77.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-130, 0, 550, 380);

        setBounds(500, 200, 420, 336);
    }// </editor-fold>//GEN-END:initComponents

    private void kecilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kecilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kecilActionPerformed

    private void sedangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sedangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sedangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String hasil9;

        if(besar.isSelected())
            hasil9 = "Anda egois";
        else if(sedang.isSelected())
            hasil9 = "Anda biasa-biasa saja";
        else
            hasil9 = "Anda baik hati";

        new Hasil9(hasil9).setVisible(true);        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(soal9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(soal9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(soal9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(soal9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new soal9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton besar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton kecil;
    private javax.swing.JRadioButton sedang;
    // End of variables declaration//GEN-END:variables
}
