/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AlifM
 */
public class soal10 extends javax.swing.JFrame {

    /**
     * Creates new form soal10
     */
    public soal10() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        kuda = new javax.swing.JRadioButton();
        lari = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        kotakbesar = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        buttonGroup1.add(kuda);
        kuda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        kuda.setText("Berlari menggunakan kuda");
        getContentPane().add(kuda);
        kuda.setBounds(20, 130, 200, 30);

        buttonGroup1.add(lari);
        lari.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lari.setText("Berlari ketempat yang lebih aman");
        lari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lariActionPerformed(evt);
            }
        });
        getContentPane().add(lari);
        lari.setBounds(20, 190, 310, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("<html> \nDisekitar daerah tersebut Anda melihat seekor kuda dan sebuah kotak besar. Oh tidak, tiba-tiba tornado datang<br> <br>\nApa yang Anda lakukan?\n\n</html>");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 380, 60);

        buttonGroup1.add(kotakbesar);
        kotakbesar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        kotakbesar.setText("Masuk kedalam kotak besar");
        kotakbesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kotakbesarActionPerformed(evt);
            }
        });
        getContentPane().add(kotakbesar);
        kotakbesar.setBounds(20, 160, 180, 30);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setText("SOAL 10");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 120, 30);

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("Lihat Hasilnya");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 243, 150, 30);

        setBounds(500, 200, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void lariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lariActionPerformed

    private void kotakbesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kotakbesarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kotakbesarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String hasil10;

        if(kuda.isSelected())
            hasil10 = "Anda membahas masalah bersama pasangan atau sahabat.";
        else if(kotakbesar.isSelected())
            hasil10 = "Anda biasa memendam masalah tersebut.";
        else
            hasil10 = "Menyelesaikan masalah sendiri.";

        new Hasil10(hasil10).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(soal10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(soal10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(soal10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(soal10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new soal10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton kotakbesar;
    private javax.swing.JRadioButton kuda;
    private javax.swing.JRadioButton lari;
    // End of variables declaration//GEN-END:variables
}
